spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            clientId: 6ae014b94a5745608749999456468265
            clientSecret: 4b238433faf840e396db02f34be27450
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            clientName: Yandex
          google:
            client-id: 349687332696-5qg4u6g7cggr9e7d2mglslir4k3i2kpr.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub